import { Movie } from './types';

export const featuredMovie: Movie = {
  id: 'the-hollow-house',
  title: 'The Hollow House',
  description:
    'A family moves into a centuries-old farmhouse only to discover that something ancient and hungry lives beneath the floorboards. As the walls begin to whisper, they must uncover the house\'s dark history before it consumes them all.',
  genre: 'Supernatural Horror',
  year: 2024,
  rating: 'R',
  duration: '1h 47m',
  matchPercent: 97,
  gradient: 'linear-gradient(135deg, #1a0000 0%, #0d0d0d 30%, #000 100%)',
  isOriginal: true,
  categories: ['trending', 'supernatural'],
};

export const movies: Movie[] = [
  {
    id: 'static-in-the-walls',
    title: 'Static in the Walls',
    description: 'A podcast crew explores a silent apartment where every floor records whispers.',
    genre: 'Paranormal',
    year: 2024,
    rating: 'TV-14',
    duration: '8 Episodes',
    matchPercent: 92,
    gradient: 'linear-gradient(160deg, #1a0a2e 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending', 'supernatural'],
  },
  {
    id: 'the-last-broadcast-booth',
    title: 'The Last Broadcast Booth',
    description: 'A late-night host takes calls from listeners predicting crimes before they happen.',
    genre: 'Thriller',
    year: 2023,
    rating: 'TV-MA',
    duration: '1h 58m',
    matchPercent: 89,
    gradient: 'linear-gradient(160deg, #2e0a0a 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending', 'psychological'],
  },
  {
    id: 'ashwood-county',
    title: 'Ashwood County',
    description: 'A sheriff reopens a missing-person case tied to an abandoned carnival.',
    genre: 'Mystery',
    year: 2024,
    rating: 'TV-MA',
    duration: '10 Episodes',
    matchPercent: 95,
    gradient: 'linear-gradient(160deg, #0a1a0a 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending', 'true-events'],
  },
  {
    id: 'neon-hollow',
    title: 'Neon Hollow',
    description: 'In a near-future city, people can rent fear as entertainment — until it escapes.',
    genre: 'Sci-fi Horror',
    year: 2025,
    rating: 'R',
    duration: '1h 42m',
    matchPercent: 88,
    gradient: 'linear-gradient(160deg, #0a0a2e 0%, #1a0020 50%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending', 'new-releases', 'sci-fi'],
  },
  {
    id: 'the-salt-chapel',
    title: 'The Salt Chapel',
    description: 'Documentary-style series about modern myths that shouldn\'t exist.',
    genre: 'Found Footage',
    year: 2023,
    rating: 'TV-14',
    duration: '6 Episodes',
    matchPercent: 84,
    gradient: 'linear-gradient(160deg, #1a1a0a 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending', 'true-events'],
  },
  {
    id: 'echo-lake-tapes',
    title: 'Echo Lake Tapes',
    description: 'Three teens uncover recordings left by a filmmaker who vanished in 1987.',
    genre: 'Coming-of-age Horror',
    year: 2024,
    rating: 'PG-13',
    duration: '1h 34m',
    matchPercent: 91,
    gradient: 'linear-gradient(160deg, #0a1a2e 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['trending'],
  },
  {
    id: 'nocturne-house',
    title: 'Nocturne House',
    description: 'Weekly anthology of one-house stories gone wrong.',
    genre: 'Anthology',
    year: 2024,
    rating: 'TV-MA',
    duration: '12 Episodes',
    matchPercent: 93,
    gradient: 'linear-gradient(160deg, #2e0a1a 0%, #0d0d0d 100%)',
    isOriginal: true,
    categories: ['trending', 'supernatural'],
  },
  {
    id: 'thread-of-dread',
    title: 'Thread of Dread',
    description: 'A fashion empire with a ritual stitched into every design.',
    genre: 'Occult Thriller',
    year: 2025,
    rating: 'TV-MA',
    duration: '8 Episodes',
    matchPercent: 86,
    gradient: 'linear-gradient(160deg, #1a0a1a 0%, #0d0d0d 100%)',
    isOriginal: true,
    categories: ['new-releases', 'psychological'],
  },
  {
    id: 'depth-signal',
    title: 'Depth Signal',
    description: 'A rescue mission receives messages from below the seabed.',
    genre: 'Sci-fi Horror',
    year: 2024,
    rating: 'R',
    duration: '1h 51m',
    matchPercent: 90,
    gradient: 'linear-gradient(160deg, #0a0a1a 0%, #001a2e 50%, #0d0d0d 100%)',
    isOriginal: true,
    categories: ['sci-fi'],
  },
  {
    id: 'tomorrow-sleeps',
    title: 'Tomorrow Sleeps',
    description: 'A city where everyone dreams the same nightmare.',
    genre: 'Psychological Horror',
    year: 2025,
    rating: 'TV-MA',
    duration: '6 Episodes',
    matchPercent: 87,
    gradient: 'linear-gradient(160deg, #1a0a0a 0%, #0d0d1a 50%, #0d0d0d 100%)',
    isOriginal: true,
    categories: ['new-releases', 'psychological'],
  },
  // ── New movies ──
  {
    id: 'the-wailing-dark',
    title: 'The Wailing Dark',
    description: 'A blind medium is summoned to a lighthouse where the dead refuse to leave.',
    genre: 'Supernatural Horror',
    year: 2025,
    rating: 'R',
    duration: '1h 53m',
    matchPercent: 94,
    gradient: 'linear-gradient(160deg, #0d1a2e 0%, #0a0a14 100%)',
    isOriginal: true,
    categories: ['new-releases', 'supernatural'],
  },
  {
    id: 'skin-walker-ridge',
    title: 'Skin Walker Ridge',
    description: 'Hikers in the Appalachian wilderness realize the trail is following them back.',
    genre: 'Folk Horror',
    year: 2025,
    rating: 'R',
    duration: '1h 39m',
    matchPercent: 91,
    gradient: 'linear-gradient(160deg, #1a1a00 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['new-releases', 'supernatural', 'true-events'],
  },
  {
    id: 'the-red-frequency',
    title: 'The Red Frequency',
    description: 'A numbers station broadcasts coordinates to places that don\'t exist on any map.',
    genre: 'Sci-fi Horror',
    year: 2026,
    rating: 'TV-MA',
    duration: '8 Episodes',
    matchPercent: 89,
    gradient: 'linear-gradient(160deg, #2e0000 0%, #0d0a1a 100%)',
    isOriginal: true,
    categories: ['new-releases', 'sci-fi'],
  },
  {
    id: 'hollowbrook-experiment',
    title: 'The Hollowbrook Experiment',
    description: 'Declassified footage from a 1970s government study on fear reveals something the scientists couldn\'t explain.',
    genre: 'Found Footage',
    year: 2024,
    rating: 'R',
    duration: '1h 28m',
    matchPercent: 86,
    gradient: 'linear-gradient(160deg, #1a1a1a 0%, #0a0d0a 100%)',
    isOriginal: false,
    categories: ['true-events', 'psychological'],
  },
  {
    id: 'beneath-the-sermon',
    title: 'Beneath the Sermon',
    description: 'A small-town preacher\'s congregation discovers his miracles come at an unspeakable price.',
    genre: 'Religious Horror',
    year: 2024,
    rating: 'TV-MA',
    duration: '6 Episodes',
    matchPercent: 92,
    gradient: 'linear-gradient(160deg, #2e1a0a 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['psychological', 'true-events'],
  },
  {
    id: 'mirror-bloom',
    title: 'Mirror Bloom',
    description: 'A photographer notices her subjects are aging rapidly — but only in the photos.',
    genre: 'Psychological Horror',
    year: 2025,
    rating: 'PG-13',
    duration: '1h 44m',
    matchPercent: 88,
    gradient: 'linear-gradient(160deg, #1a0020 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['new-releases', 'psychological'],
  },
  {
    id: 'the-ossuary',
    title: 'The Ossuary',
    description: 'Construction workers uncover a bone cathedral beneath a European city and awaken its architect.',
    genre: 'Supernatural Horror',
    year: 2026,
    rating: 'R',
    duration: '1h 56m',
    matchPercent: 93,
    gradient: 'linear-gradient(160deg, #1a0a00 0%, #0a0a1a 100%)',
    isOriginal: true,
    categories: ['new-releases', 'supernatural'],
  },
  {
    id: 'dead-air',
    title: 'Dead Air',
    description: 'An overnight radio DJ takes a call from someone who says they\'re broadcasting from the future.',
    genre: 'Sci-fi Horror',
    year: 2024,
    rating: 'TV-14',
    duration: '10 Episodes',
    matchPercent: 90,
    gradient: 'linear-gradient(160deg, #0a1a1a 0%, #0d000d 100%)',
    isOriginal: false,
    categories: ['sci-fi', 'trending'],
  },
  {
    id: 'the-binding-of-ruth',
    title: 'The Binding of Ruth',
    description: 'A true-crime podcast investigating a cult in rural Oregon finds the cult has been investigating them.',
    genre: 'True Crime Horror',
    year: 2024,
    rating: 'TV-MA',
    duration: '8 Episodes',
    matchPercent: 95,
    gradient: 'linear-gradient(160deg, #0a0a0a 0%, #1a0a0a 100%)',
    isOriginal: false,
    categories: ['true-events', 'psychological'],
  },
  {
    id: 'somnia',
    title: 'Somnia',
    description: 'A sleep clinic\'s patients begin sharing the same impossible dreamscape — and one by one, they stop waking up.',
    genre: 'Psychological Horror',
    year: 2025,
    rating: 'R',
    duration: '1h 49m',
    matchPercent: 91,
    gradient: 'linear-gradient(160deg, #14001a 0%, #0d0d1a 100%)',
    isOriginal: true,
    categories: ['new-releases', 'psychological', 'sci-fi'],
  },
  {
    id: 'rot',
    title: 'Rot',
    description: 'A biologist studying fungal networks in old-growth forests realizes the mycelium is thinking.',
    genre: 'Eco Horror',
    year: 2026,
    rating: 'R',
    duration: '1h 38m',
    matchPercent: 87,
    gradient: 'linear-gradient(160deg, #0a1a00 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['new-releases', 'sci-fi'],
  },
  {
    id: 'the-seventh-floor',
    title: 'The Seventh Floor',
    description: 'Residents of an apartment building discover their seventh floor doesn\'t exist — except at 3 AM.',
    genre: 'Supernatural Horror',
    year: 2024,
    rating: 'TV-MA',
    duration: '8 Episodes',
    matchPercent: 93,
    gradient: 'linear-gradient(160deg, #0d0d2e 0%, #0d0d0d 100%)',
    isOriginal: false,
    categories: ['supernatural', 'trending'],
  },
  {
    id: 'blackwater-gospel',
    title: 'Blackwater Gospel',
    description: 'A missionary expedition up a remote river encounters a village that worships something in the water.',
    genre: 'Folk Horror',
    year: 2025,
    rating: 'R',
    duration: '1h 46m',
    matchPercent: 90,
    gradient: 'linear-gradient(160deg, #001a0d 0%, #0a0a0a 100%)',
    isOriginal: false,
    categories: ['new-releases', 'supernatural', 'true-events'],
  },
  {
    id: 'the-cartographer',
    title: 'The Cartographer',
    description: 'An antique map collector finds a chart of a city that appears to be drawing itself in real time.',
    genre: 'Psychological Horror',
    year: 2024,
    rating: 'PG-13',
    duration: '1h 41m',
    matchPercent: 85,
    gradient: 'linear-gradient(160deg, #1a1a0d 0%, #0d0a1a 100%)',
    isOriginal: false,
    categories: ['psychological'],
  },
  {
    id: 'frequencies-of-fear',
    title: 'Frequencies of Fear',
    description: 'Sound engineers discover an infrasound frequency that makes listeners see their own death.',
    genre: 'Sci-fi Horror',
    year: 2026,
    rating: 'R',
    duration: '1h 52m',
    matchPercent: 88,
    gradient: 'linear-gradient(160deg, #0a0d1a 0%, #1a0a0d 100%)',
    isOriginal: true,
    categories: ['new-releases', 'sci-fi'],
  },
  {
    id: 'the-quarantine-tapes',
    title: 'The Quarantine Tapes',
    description: 'Found footage from a sealed research bunker reveals the crew didn\'t die from the virus.',
    genre: 'Found Footage',
    year: 2023,
    rating: 'R',
    duration: '1h 22m',
    matchPercent: 83,
    gradient: 'linear-gradient(160deg, #1a1a0a 0%, #0a0d0d 100%)',
    isOriginal: false,
    categories: ['true-events'],
  },
  {
    id: 'mother-of-crows',
    title: 'Mother of Crows',
    description: 'A grandmother in rural Appalachia guards a secret that has kept her family alive for two hundred years.',
    genre: 'Folk Horror',
    year: 2025,
    rating: 'TV-MA',
    duration: '6 Episodes',
    matchPercent: 94,
    gradient: 'linear-gradient(160deg, #0d0a00 0%, #1a0d0d 100%)',
    isOriginal: true,
    categories: ['new-releases', 'supernatural'],
  },
];

export const allMovies: Movie[] = [featuredMovie, ...movies];

export const categories = [
  { title: 'Trending Now', key: 'trending' },
  { title: 'DREADFLIX Originals', key: 'originals' },
  { title: 'New Releases', key: 'new-releases' },
  { title: 'Supernatural', key: 'supernatural' },
  { title: 'Psychological Horror', key: 'psychological' },
  { title: 'Sci-Fi Horror', key: 'sci-fi' },
  { title: 'Based on True Events', key: 'true-events' },
] as const;

export function getMoviesForCategory(key: string): Movie[] {
  if (key === 'originals') {
    return allMovies.filter((m) => m.isOriginal);
  }
  return allMovies.filter((m) => m.categories.includes(key));
}

export const genres = [
  'All',
  'Supernatural Horror',
  'Psychological Horror',
  'Sci-fi Horror',
  'Folk Horror',
  'Found Footage',
  'Thriller',
  'Mystery',
  'Anthology',
  'Eco Horror',
] as const;
